---
title: "Prices (Demo)"
author: "HedgeMaster Challenge 2016"
date: "November 13, 2016"
output: pdf_document
---

```{r, echo = FALSE, results='hide'}
suppressMessages({
      library(knitr)
      MAINCODEDIR <- "C:/Users/User/Google Drive/z_ALLHM/_MainCode"
      setwd(MAINCODEDIR)
      source("_HM_allfunction.R")
      
            
})

meta.dir <- "C:/Users/User/Google Drive/z_ALLHM/6.0_meta_Demo"

      yr <- 1


elink <- c("https://1drv.ms/xs/s!AuUxik9_I7qcjiBQfnoqJg3zA6sP",
           "https://1drv.ms/xs/s!AuUxik9_I7qcjiO8udmmD0eQQu9k",
           "https://1drv.ms/xs/s!AuUxik9_I7qcjiWKEYvWr8Do8hmA", 
           "https://1drv.ms/xs/s!AuUxik9_I7qcjiiW9uRcOHZ86EU3",
           "https://1drv.ms/xs/s!AuUxik9_I7qcjidakuac0BAtb0-u")

```

```{r, echo = F, fig.width= 1000}
setwd(meta.dir)
undraw.df <- as.data.frame(read_excel("meta-underlyingprice.xlsx"))

UnderlyingAsset <- colnames(undraw.df)[2:9]
if(yr %in% 0){
      Price0 <- rep(NA, 8)
}else{
      Price0 <- as.numeric(undraw.df[yr, 2:9])
}
Price1 <- as.numeric(undraw.df[yr+1, 2:9])
Currency <- c("USD", "MYR", "MYR", "MYR", "MYR", NA, NA, NA)
Description <- c("GOL = Gold", "CRU = Crude Oil", "PAL = Palm Oil",
                 "USD = US Dollar", "EUR = Euro Dollar", "1 year Malaysia T-Bill rate",
                 "1 year US T-Bill rate", "1 year Euro zone T-Bill rate")
und.df <- data.frame(UnderlyingAsset, Price0, Price1, Currency)
und2.df <- data.frame(UnderlyingAsset, Description)

c2 <- paste0("Price per unit \\\n(END of YEAR ", yr-1, ")")
c3 <- paste0("Price per unit \\\n(END of YEAR ", yr, ")")

colnames(und.df) <- c("Underlying \\\nAsset/Indicators", c2,c3, "Currency \\\nDenomination")
colnames(und2.df) <- c("Underlying \\\nAsset/Indicators", "Description")


```

#Prices
##End of Year `r yr` 

###Prices of non-tradeable asset/Indicators
```{r, echo=FALSE}
pander(und.df, keep.line.breaks = TRUE)
pander(und2.df, keep.line.breaks = TRUE)
```



